version: '3'

services:
  sfm-bot:
    container_name: sfm-price-bot
    build:
      dockerfile: Dockerfile
    pull_policy: build
    env_file:
      - stack.env
    restart: unless-stopped
    network_mode: "host"
