version: '3'

services:
  sfm-bot:
    container_name: sfm-price-bot
    build:
      dockerfile: Dockerfile
    pull_policy: build
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: 10.10.2.36

networks:
  lan:
    name: LAN
    external: true
